{
 "title": "Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    count(count(node_cpu_seconds_total{job=\"node_export\"}) by (cpu))\n    - avg(sum by (mode)(rate(node_cpu_seconds_total{job=\"node_export\", mode=\"idle\"}[5m])))\n  ) * 100\n) / count(count(node_cpu_seconds_total{job=\"node_export\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_export\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node_export\"} * 100) /node_memory_MemTotal_bytes{job=\"node_export\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_export\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_export\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_export\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_export\"} - node_boot_time_seconds{job=\"node_export\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node_export\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{job=\"node_export\"}",
     "legendFormat": "{{collector}} - Scrape duration"
    }
   ]
  },
  {
   "title": "Network Trafffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_export\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node_export\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "MYSQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{job=\"mysql_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_queries{job=\"mysql_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MYSQL Table Locks",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_table_locks_immediate{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_status_table_locks_waited",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MYSQL Up Time ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{job=\"mysql_instance\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MYSQL Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_bytes_received{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_status_bytes_sent{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MYSQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 29 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_variables_max_connections{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_status_max_used_connections{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MYSQL Internal Memory Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_variables_key_buffer_size{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_variables_have_query_cache{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mysql_global_variables_innodb_adaptive_hash_index{job=\"mysql_instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Head Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 50 },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds_sum{job=\"prometheus\"}",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}